root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  args_bin = []
  bin = "./bin/main"
  cmd = "go build -gcflags='all=-N -l' -o ./bin/main ./cmd/api"
  delay = 1000
  exclude_dir = ["assets", "bin", "vendor", "testdata", "web", "docs", "scripts"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "if [ \"$DEBUG\" = \"true\" ]; then $HOME/go/bin/dlv exec --accept-multiclient --log --headless --continue --listen :2345 --api-version 2 ./bin/main; else ./bin/main; fi"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["make gen-docs"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  application = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
