version: "3.8"

services:
    postgres:
        image: postgres:15-alpine
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-admin}"]
            interval: 2s
            timeout: 5s
            retries: 5
            start_period: 5s

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        env_file:
            - .env
        environment:
            DB_HOST: postgres
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
        volumes:
            - ./migrations:/app/migrations

volumes:
    postgres_data:
