services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADDR: ":8080"
      API_URL: "localhost:8080"
      FRONTEND_URL: "http://localhost:5173"
      DB_ADDR: "postgres://admin:adminpassword@psql_bp/jono-poll-db?sslmode=disable"
      DB_MAX_OPEN_CONNS: "30"
      DB_MAX_IDLE_CONNS: "30"
      DB_MAX_IDLE_TIME: "15m"
      RATELIMITER_REQUESTSPERTIMEFRAME: "20"
      RATELIMITER_TIMEFRAME: "5s"
      RATELIMITER_ENABLED: "true"
    depends_on:
      psql_bp:
        condition: service_healthy
    networks:
      - blueprint
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: jono-poll-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_base:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${ECHO_BASE_DB_USERNAME} -d ${ECHO_BASE_DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - blueprint

volumes:
  psql_volume_base:
networks:
  blueprint:
