version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - backend
    volumes:
      - Postdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  my-db:
    image: mysql:8.4.2
    restart: unless-stopped
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: LocalDB
      MYSQL_ROOT_PASSWORD: becareful
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - MySQL-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - backend


#  redis:
#    image: redis:6.2-alpine
#    restart: unless-stopped
#    container_name: redis
#    ports:
#      - "6379:6379"
#    command: redis-server --save 60 1 --loglevel warning
#
#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOST=redis
#    ports:
#      - "127.0.0.1:8081:8081"
#    depends_on:
#      - redis
#    restart:
#      unless-stopped

volumes:
  MySQL-data:
  Postdb-data:

networks:
  backend:
    driver: bridge