addr: ":8080"
apiURL: "localhost:8080"
frontendURL: "http://localhost:5173"
db:
  addr: "postgres://admin:adminpassword@localhost/socialnetwork?sslmode=disable"
  maxOpenConns: 30
  maxIdleConns: 30
  maxIdleTime: "15m"
redisCfg:
  addr: "localhost:6379"
  pw: ""
  db: 0
  enabled: false
env: "development"
mail:
  exp: "72h"  # 3 days
  fromEmail: ""
  sendGrid:
    apiKey: ""
auth:
  basic:
    user: "admin"
    pass: "admin"
  token:
    secret: "example"
    exp: "72h"  # 3 days
    iss: "gophersocial"
rateLimiter:
  requestsPerTimeFrame: 20
  timeFrame: "5s"
  enabled: true