definitions:
  poll.CreatePollRequest:
    properties:
      options:
        example:
        - '['
        items:
          type: string
        type: array
      question:
        example: What is your favorite programming language?
        type: string
    type: object
  poll.CreatePollResponse:
    properties:
      poll:
        $ref: '#/definitions/poll.Poll'
    type: object
  poll.Option:
    properties:
      id:
        type: integer
      poll_id:
        type: integer
      text:
        type: string
      votes:
        type: integer
    type: object
  poll.Poll:
    properties:
      created_at:
        type: string
      id:
        type: integer
      options:
        items:
          $ref: '#/definitions/poll.Option'
        type: array
      question:
        type: string
      user_id:
        type: integer
    type: object
  poll.PollResultsResponse:
    properties:
      created_at:
        type: string
      options:
        items:
          $ref: '#/definitions/poll.Option'
        type: array
      poll_id:
        example: 1
        type: integer
      question:
        example: What is your favorite programming language?
        type: string
      total_votes:
        example: 42
        type: integer
    type: object
  poll.VotePollRequest:
    properties:
      option_id:
        example: 1
        type: integer
    type: object
  poll.VotePollResponse:
    properties:
      message:
        example: Vote recorded successfully
        type: string
      option_id:
        example: 2
        type: integer
      poll_id:
        example: 1
        type: integer
      timestamp:
        example: "2025-05-18T10:30:45Z"
        type: string
    type: object
  response.FailedResponse:
    properties:
      code:
        description: HTTP status code.
        example: 500
        type: integer
      error:
        description: error message.
        example: '{$err}'
        type: string
      message:
        description: Message corresponding to the status code.
        example: internal_server_error
        type: string
    type: object
  user.LoginRequest:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: securePassword123
        type: string
    required:
    - email
    - password
    type: object
  user.RegisterRequest:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: securePassword123
        type: string
      username:
        example: johndoe
        type: string
    required:
    - email
    - password
    type: object
  user.TokenResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  user.User:
    properties:
      created_at:
        example: "2023-01-01T12:00:00Z"
        type: string
      email:
        example: john@example.com
        type: string
      id:
        example: 1
        type: integer
      is_active:
        example: true
        type: boolean
      username:
        example: johndoe
        type: string
    type: object
info:
  contact: {}
  description: A simple poll and voting API with user authentication
  title: JonoMot
  version: 0.1.0
paths:
  /api/v1/poll:
    post:
      consumes:
      - application/json
      description: Create a new poll with a question and multiple options
      parameters:
      - description: Poll creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/poll.CreatePollRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created poll
          schema:
            $ref: '#/definitions/poll.CreatePollResponse'
        "400":
          description: Bad request - invalid input
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "401":
          description: Unauthorized - authentication required
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      security:
      - BearerAuth: []
      summary: Create a new poll
      tags:
      - polls
  /api/v1/poll/{id}:
    get:
      consumes:
      - application/json
      description: Get poll details including available options
      parameters:
      - description: Poll ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Poll details with options
          schema:
            $ref: '#/definitions/poll.Poll'
        "400":
          description: Bad request - invalid ID format
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "404":
          description: Not found - poll doesn't exist
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      summary: Get poll information
      tags:
      - polls
  /api/v1/poll/{id}/results:
    get:
      consumes:
      - application/json
      description: Get the current vote counts for each option in a poll
      parameters:
      - description: Poll ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Poll results with options and vote counts
          schema:
            $ref: '#/definitions/poll.PollResultsResponse'
        "400":
          description: Bad request - invalid poll ID format
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "404":
          description: Not found - poll doesn't exist
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      summary: Get poll results
      tags:
      - polls
  /api/v1/poll/{id}/vote:
    post:
      consumes:
      - application/json
      description: Submit a vote for a specific option in a poll
      parameters:
      - description: Poll ID
        in: path
        name: id
        required: true
        type: integer
      - description: Vote details with option_id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/poll.VotePollRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Vote successfully recorded with details
          schema:
            $ref: '#/definitions/poll.VotePollResponse'
        "400":
          description: Bad request - invalid input or poll ID
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "401":
          description: Unauthorized - authentication required
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "403":
          description: Forbidden - user has already voted
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      security:
      - BearerAuth: []
      summary: Vote on a poll
      tags:
      - polls
  /api/v1/user/{id}:
    get:
      consumes:
      - application/json
      description: Get user details by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad request - invalid ID format
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "404":
          description: Not found - user doesn't exist
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - users
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token
      parameters:
      - description: User login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated with JWT token
          schema:
            $ref: '#/definitions/user.TokenResponse'
        "400":
          description: Bad request - invalid input
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "401":
          description: Unauthorized - invalid credentials
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      summary: User login
      tags:
      - users
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: Create a new user account with username, email, and password
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully registered user
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad request - invalid input
          schema:
            $ref: '#/definitions/response.FailedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.FailedResponse'
      summary: Register a new user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Enter your JWT token directly (or optionally with 'Bearer ' prefix)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
